version: "3"
services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - ./config/dev.env
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=damilola
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes:
      - mongo-db:/data/db
  redis:
    image: redis

volumes:
  mongo-db:
