name: API Tests
on: push
jobs:
  run-contract-tests:
    name: Run contract tests
    runs-on: ubuntu-latest
    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup node 14
        uses: actions/setup-node@v1
        with:
          node-version: 16.3.0
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.lock') }}
      - name: install node packages
        if: steps.cache.outputs.cache-hit != 'true'
        id: install_node_packages
        run: |
          npm install
      - name: run api tests
        id: run_api_tests
        run: |
          npm run test
